services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-ShelterProject
    env_file:
      - .env
    environment:
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - ShelterNetwork
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: "exit 0"

  app:
    depends_on:
      mysql:
        condition: service_healthy
    build: ./ShelterMonitor
    env_file:
      - .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_DOCKER_PORT
    networks:
      - ShelterNetwork
volumes:
  mysql_data:

networks:
  ShelterNetwork:
    driver: bridge